import AppKit
import CryptoKit

struct ClipPayload {
    let kind: ClipKind
    let text: String?
    let rtfData: Data?
    let imageData: Data?
    let fileURLs: [URL]
    let sourceAppName: String?
    let sourceAppBundleID: String?

    var contentHash: String {
        switch kind {
        case .text:
            return Self.sha256(Data((text ?? "").utf8))
        case .image:
            return Self.sha256(imageData ?? Data())
        case .files:
            let joined = fileURLs.map(\.standardizedFileURL.path).joined(separator: "\n")
            return Self.sha256(Data(joined.utf8))
        }
    }

    static func read(from pasteboard: NSPasteboard) -> ClipPayload? {
        guard !isIgnored(pasteboard) else { return nil }

        let source = NSWorkspace.shared.frontmostApplication

        if let urls = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !urls.isEmpty {
            return ClipPayload(
                kind: .files,
                text: nil,
                rtfData: nil,
                imageData: nil,
                fileURLs: urls,
                sourceAppName: source?.localizedName,
                sourceAppBundleID: source?.bundleIdentifier
            )
        }

        if let png = pngData(from: pasteboard) {
            return ClipPayload(
                kind: .image,
                text: nil,
                rtfData: nil,
                imageData: png,
                fileURLs: [],
                sourceAppName: source?.localizedName,
                sourceAppBundleID: source?.bundleIdentifier
            )
        }

        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return ClipPayload(
                kind: .text,
                text: string,
                rtfData: pasteboard.data(forType: .rtf),
                imageData: nil,
                fileURLs: [],
                sourceAppName: source?.localizedName,
                sourceAppBundleID: source?.bundleIdentifier
            )
        }

        return nil
    }

    // Types marked by password managers and other tools as sensitive or ephemeral.
    private static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]

    private static func isIgnored(_ pasteboard: NSPasteboard) -> Bool {
        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        return !types.isDisjoint(with: ignoredTypes)
    }

    private static func pngData(from pasteboard: NSPasteboard) -> Data? {
        if let png = pasteboard.data(forType: .png) {
            return png
        }
        if let tiff = pasteboard.data(forType: .tiff),
           let rep = NSBitmapImageRep(data: tiff),
           let png = rep.representation(using: .png, properties: [:]) {
            return png
        }
        return nil
    }

    private static func sha256(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }
}
